### ISSUE TITLE
Readme installation instructions aren't clear

### ISSUE THREAD

**Issue by johnalarcon** [bahiirwa/ClassicPressPetitionsDashboard#2]
> 1. Upload the plugin to the /wp-content/plugins/ directory or from the repository...

Everything after the word "or" makes no sense.

> 3. Refer to plugin description in regards to setting up how the plugins works

Which description? In the plugin header, in the readme, or ... Actually, it looks like there are no setup steps other than these steps that are listed.

> 4. It will work out of the box. Move to your media library and you can unattach and re-attach attachments to various posts.

No idea what this means.

**Comment by bahiirwa** [comment]
Huge oversight due to lack of sleep and Copy-Paste-edit. Cleaned it out

**Comment by johnalarcon** [comment]
For item 1, I think you're trying to say:

1. Upload the plugin to the /wp-content/plugins/ directory or [install directly] from the repository.

**Comment by bahiirwa** [comment]
Thanks. I have added that to docs

**Comment by johnalarcon** [comment]
The brackets didn't actually need to go in item 1. Sorry for the confusion. I was just trying to indicate where the change was. :)

**Comment by bahiirwa** [comment]
Thank you for the keen eye.
