### ISSUE TITLE
Use wp_remote_get() instead of file_get_contents()

### ISSUE THREAD

**Issue by mikeschinkel** [bahiirwa/ClassicPressPetitionsDashboard#3]
You might consider using [wp_remote_get()](https://codex.wordpress.org/Function_Reference/wp_remote_get) instead of [file_get_contents()](https://github.com/bahiirwa/ClassicPressPetitionsDashboard/blob/d2c8d70b5e3edb302f5ed5a1031800510b25aa9c/ClassicPressPetitionsDashboard.php#L44) because [many web hosts lock down URL requests via `file_get_contents()`](https://www.google.com/search?q=php+file_get_contents+url+not+working).

#fwiw

**Comment by bahiirwa** [comment]
Thanks for the heads up. I have incorporated the function. Check it out now.
