### ISSUE TITLE
Color code the status

### ISSUE THREAD

**Issue by bahiirwa** [bahiirwa/ClassicPressPetitionsDashboard#5]
I am thinking as a design element to color the status of the different petitions so that they can be distinct. is this a good way to go?

**Comment by striebwj** [comment]
We were chatting about not showing the status when it is set to open. This may be a way to go so the status is only shown when it is set to "planned" or "started".

**Comment by bahiirwa** [comment]
That makes sense. In essence all topics/petitions are open by default. Is there a comprehensive way of knowing all the available statuses?

**Comment by striebwj** [comment]
The only two that should come into play, other than open, are "planned" and "started". Once listed as "completed", "duplicate", or "declined" they are removed from the main view and don't show up in this API call (at least from my testing).

**Comment by bahiirwa** [comment]
Fixed with 
```
span.planned {
  display: inline;
  background: #89288f; /* 61ce70 is the classic green but a pain to read */
  color: #fff;
  padding: 2px 4px;
}

span.started {
  display: inline;
  background: #1da21d;
  color: #fff;
  padding: 2px 4px;
}
```
