### ISSUE TITLE
Show categories Ending, most wanted or recent petitions

### ISSUE THREAD

**Issue by bahiirwa** [bahiirwa/ClassicPressPetitionsDashboard#6]
Following https://github.com/bahiirwa/ClassicPressPetitionsDashboard/pull/4, there is a need to make a dropdown that allows a user to choose to see the trending, most wanted or recent petitions made.

**Comment by striebwj** [comment]
As discussed on Slack, I agree that Javascript may be the best solution here. We will need to find a clean/user-friendly way to allow that though.

**Comment by bahiirwa** [comment]
Fetchor axios? Vanilla vs JQuery ?

**Comment by striebwj** [comment]
Tabs I think are a good option for now. There was a lengthy discussion on Slack regarding this - I tagged you in it (https://classicpress.slack.com/archives/CDGP8FW56/p1543435546055500?thread_ts=1543435531.055400&cid=CDGP8FW56)

**Comment by bahiirwa** [comment]
Thanks for taking this on. Sorry I have been out of action. Any PR? I can do some enhancements.

**Comment by striebwj** [comment]
No worries! Ia have made some progress I'll submit a PR this afternoon. I posted a screenshot on Slack.

**Comment by striebwj** [comment]
Got to it this morning, submitted #8
